# -*- coding: utf-8 -*-
"""tratar_simples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13R-WPVH_5CRm_s711UomhKf1WKOgQEMI
"""

import os
import zipfile
import cv2
from google.colab.patches import cv2_imshow

from google.colab import drive
drive.mount('/content/drive')

cam = '/content/homer_bart_1'
cpt = zipfile.ZipFile(file = cam, mode='r')
cpt.extractall('./')
cpt.close

igm = cv2.imread('/content/homer_bart_1/bart1.bmp')
cv2_imshow(igm)

d = '/content/homer_bart_1'
arq = [os.path.join(d, f) for f in sorted(os.listdir(d))]
arq

imagens = []
target = []
altura, largura = 128, 128
cont=0

for caminho_imagem in arq:
  try:
    imagem = cv2.imread(caminho_imagem)
    (H, W) = imagem.shape[:2]
  except:
    continue
  cont+=1
  imagem = cv2.resize(imagem, (altura, largura))
  imagem = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
  cv2_imshow(imagem)

  imagem = imagem.ravel()
  imagens.append(imagem)

  #agora vamos criar o target da imagem
  nome_imagem = os.path.basename(os.path.normpath(caminho_imagem))
  if nome_imagem.startswith('b'):
    classe = 0
  else:
    classe = 1
  target.append(classe)
  print(classe)