# -*- coding: utf-8 -*-
"""tratarimagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16UGIRqXcRgweqVJR4NiDyiEjFOo6spWS
"""

import os
import zipfile
import cv2
from google.colab.patches import cv2_imshow

from google.colab import drive
drive.mount('/content/drive')

cam = '/content/drive/MyDrive/VC/Cópia de cat_dog_2-20230803T132654Z-001.zip'
cpt = zipfile.ZipFile(file = cam, mode='r')
cpt.extractall('./')
cpt.close

igm = cv2.imread('/content/cat_dog_2/training_set/cat/cat.0.jpg')
cv2_imshow(igm)
igm2 = cv2.imread('/content/cat_dog_2/training_set/dog/dog.0.jpg')
cv2_imshow(igm2)

d1 = '/content/cat_dog_2/training_set/cat'
arq1 = [os.path.join(d1, f) for f in sorted(os.listdir(d1))]
arq1
d2 = '/content/cat_dog_2/training_set/dog'
arq2 = [os.path.join(d2, f) for f in sorted(os.listdir(d2))]
arq2

vetimg = []
espc = []
altura, largura = 128, 128
cont=0

for cam in arq1:
  try:
    imagem = cv2.imread(cam)
    (H, W) = imagem.shape[:2]
  except:
    continue
  cont+=1
  imagem = cv2.resize(imagem, (altura, largura))
  imagem = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
  cv2_imshow(imagem)

  imagem = imagem.ravel()
  vetimg.append(imagem)

  nome_imagem = os.path.basename(os.path.normpath(cam))
  if nome_imagem.startswith('b'):
    classe = 0
  else:
    classe = 1
  espc.append(classe)
  print(classe)

for cam in arq2:
  try:
    imagem = cv2.imread(cam)
    (H, W) = imagem.shape[:2]
  except:
    continue
  cont+=1
  imagem = cv2.resize(imagem, (altura, largura))
  imagem = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
  cv2_imshow(imagem)

  imagem = imagem.ravel()
  vetimg.append(imagem)

  nome_imagem = os.path.basename(os.path.normpath(cam))
  if nome_imagem.startswith('d'):
    classe = 0
  else:
    classe = 1
  espc.append(classe)
  print(classe)